In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import os

In [12]:
df = pd.read_csv('../data/raw/Rekrute.csv')

In [14]:
df.head()

,offer_id,scrape_date,scrape_timestamp,titre_poste,entreprise,secteur_entreprise,taille_entreprise,ville,ville_normalized,region,...,date_publication,date_limite,salaire,has_salary_info,description_poste,profil_candidat,description_entreprise,site_web_entreprise,url,date_annee
0,846932618F,2026-06-16,2026-06-16T14:05:33.422004,Project Management Office (PMO),Atos,Gestion projet / Etudes / R&D- Informatique / ...,NaN,Casablanca,Casablanca,Casablanca-Settat,...,NaN,24/06/2017,NaN,0,Une nouvelle activité a pris naissance au sein...,Bac + 4/5 commerce et gestion avec une expérie...,"Atos SE (Société Européenne) , est un leader d...",NaN,https://www.rekrute.com/offre-emploi-project-m...,2016
1,35C4397FD9,2026-06-16,2026-06-16T14:05:33.740498,Stage en coordination mobilité internationale,Atos,Informatique,NaN,Casablanca,Casablanca,Casablanca-Settat,...,NaN,24/06/2017,NaN,0,Au sein du département de la mobilité internat...,"Bac+3 et plus en Management RH , ou en droit i...","Atos SE (Société Européenne) , est un leader d...",NaN,https://www.rekrute.com/offre-emploi-stage-en-...,2016
2,D3E682961F,2026-06-16,2026-06-16T14:05:33.890840,Chefs de Projets Techniques .NET,Sqli Maroc,Informatique / Electronique- Internet / Multim...,NaN,Rabat,Rabat,Rabat-Salé-Kénitra,...,NaN,24/06/2017,NaN,0,Dans le cadre de la forte croissance de nos ac...,"De formation Bac+5 en informatique, vous justi...","Créé en 1990, SQLI est le partenaire de référe...",NaN,https://www.rekrute.com/offre-emploi-chefs-de-...,2016
3,3982EE759A,2026-06-16,2026-06-16T14:05:34.188578,Développeur Front End Angular JS en CDI,Welink,Informatique / Electronique- Internet / Multim...,NaN,Rabat,Rabat,Rabat-Salé-Kénitra,...,NaN,24/06/2017,NaN,0,Au sein d'une équipe dynamique et jeune et sur...,De formation Ingénieur BAC+5 en informatique a...,Notre entreprise : WeLinK est un cabinet de Co...,NaN,https://www.rekrute.com/offre-emploi-developpe...,2016
4,2370F10D20,2026-06-16,2026-06-16T14:05:34.869485,Développeur Front End Angular JS en CDI,Welink,Informatique / Electronique- Internet / Multim...,NaN,Rabat,Rabat,Rabat-Salé-Kénitra,...,NaN,25/04/2017,NaN,0,Au sein d'une équipe dynamique et jeune et sur...,De formation Ingénieur BAC+5 en informatique a...,Notre entreprise : WeLinK est un cabinet de Co...,NaN,https://www.rekrute.com/offre-emploi-developpe...,2016

In [24]:
df.shape

(10782, 42)

In [ ]:
# View information about the DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10782 entries, 0 to 10781
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   offer_id                  10782 non-null  str
 1   scrape_date               10782 non-null  str
 2   scrape_timestamp          10782 non-null  str
 3   titre_poste               10782 non-null  str
 4   entreprise                10782 non-null  str
 5   secteur_entreprise        10782 non-null  str
 6   taille_entreprise         0 non-null      float64
 7   ville                     10782 non-null  str
 8   ville_normalized          10782 non-null  str
 9   region                    9975 non-null   str
 10  type_contrat              10768 non-null  str
 11  type_contrat_normalized   10768 non-null  str
 12  modalite_travail          10782 non-null  str
 13  is_remote                 10782 non-null  int64
 14  is_hybrid                 10782 non-null  int64
 15  is_onsite                 10782 non-null  int64
 16  niveau_etudes             10768 non-null  str
 17  niveau_etudes_normalized  10768 non-null  str
 18  experience_requise        10781 non-null  str
 19  experience_years_min      10782 non-null  int64
 20  experience_years_max      10782 non-null  int64
 21  langue                    4977 non-null   str
 22  secteur_activite          10782 non-null  str
 23  sous_secteur              4614 non-null   str
 24  fonction                  4614 non-null   str
 25  sous_fonction             0 non-null      float64
 26  hard_skills               7576 non-null   str
 27  soft_skills               10782 non-null  str
 28  tech_stack                7576 non-null   str
 29  tech_count                10782 non-null  int64
 30  soft_skills_count         10782 non-null  int64
 31  nbr_postes                9993 non-null   float64
 32  date_publication          0 non-null      float64
 33  date_limite               10782 non-null  str
 34  salaire                   63 non-null     str
 35  has_salary_info           10782 non-null  int64
 36  description_poste         10774 non-null  str
 37  profil_candidat           10754 non-null  str
 38  description_entreprise    10779 non-null  str
 39  site_web_entreprise       612 non-null    str
 40  url                       10782 non-null  str
 41  date_annee                10782 non-null  int64
dtypes: float64(4), int64(9), str(29)
memory usage: 43.9 MB

In [21]:
df.describe()

,taille_entreprise,is_remote,is_hybrid,is_onsite,experience_years_min,experience_years_max,sous_fonction,tech_count,soft_skills_count,nbr_postes,date_publication,has_salary_info,date_annee
count,0.0,10782.000000,10782.000000,10782.0,10782.000000,10782.000000,0.0,10782.000000,10782.000000,9993.000000,0.0,10782.000000,10782.000000
mean,NaN,0.794751,0.205249,0.0,3.080597,5.886848,NaN,3.493786,7.184010,3.398079,NaN,0.005843,2020.909757
std,NaN,0.403903,0.403903,0.0,1.888973,3.744110,NaN,4.176727,2.263893,7.397799,NaN,0.076220,3.116589
min,NaN,0.000000,0.000000,0.0,0.000000,0.000000,NaN,0.000000,1.000000,1.000000,NaN,0.000000,2016.000000
25%,NaN,1.000000,0.000000,0.0,1.000000,3.000000,NaN,0.000000,6.000000,1.000000,NaN,0.000000,2018.000000
50%,NaN,1.000000,0.000000,0.0,3.000000,5.000000,NaN,2.000000,7.000000,1.000000,NaN,0.000000,2021.000000
75%,NaN,1.000000,0.000000,0.0,5.000000,10.000000,NaN,5.000000,9.000000,3.000000,NaN,0.000000,2024.000000
max,NaN,1.000000,1.000000,0.0,10.000000,20.000000,NaN,31.000000,20.000000,300.000000,NaN,1.000000,2026.000000

In [22]:
df.isnull().sum()

offer_id                        0
scrape_date                     0
scrape_timestamp                0
titre_poste                     0
entreprise                      0
secteur_entreprise              0
taille_entreprise           10782
ville                           0
ville_normalized                0
region                        807
type_contrat                   14
type_contrat_normalized        14
modalite_travail                0
is_remote                       0
is_hybrid                       0
is_onsite                       0
niveau_etudes                  14
niveau_etudes_normalized       14
experience_requise              1
experience_years_min            0
experience_years_max            0
langue                       5805
secteur_activite                0
sous_secteur                 6168
fonction                     6168
sous_fonction               10782
hard_skills                  3206
soft_skills                     0
tech_stack                   3206
tech_count                      0
soft_skills_count               0
nbr_postes                    789
date_publication            10782
date_limite                     0
salaire                     10719
has_salary_info                 0
description_poste               8
profil_candidat                28
description_entreprise          3
site_web_entreprise         10170
url                             0
date_annee                      0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)