In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from scipy.stats import binomtest
from scipy.stats import chisquare
from scipy.stats import ttest_1samp
from scipy.stats import chi2_contingency
from scipy.stats import pearsonr

In [2]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
df['day'].value_counts(normalize=True)

day
Sat     0.356557
Sun     0.311475
Thur    0.254098
Fri     0.077869
Name: proportion, dtype: float64

In [4]:
f_exp = df['day'].value_counts(normalize=True).sort_index() * len(df)
f_exp

day
Thur    62.0
Fri     19.0
Sat     87.0
Sun     76.0
Name: proportion, dtype: float64

In [5]:
observed = df['day'].value_counts(normalize=True) * len(df)
observed
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:

res=  chisquare(f_obs= observed, f_exp =f_exp)
alpha = 0.02
print(res)
if res.pvalue < alpha:
    print('We reject the null hypothesis')
else:   
    print('We fail to reject the null hypothesis')

Power_divergenceResult(statistic=np.float64(231.01455320726734), pvalue=np.float64(8.345546285774406e-50))
We reject the null hypothesis

## the manager says the average of tips is 3,5 Dollar

In [7]:
tips_average = df['tip'].mean()
tips_average

np.float64(2.99827868852459)

In [8]:
res = ttest_1samp(df['tip'], 3.5).pvalue
alpha = 0.02
res

np.float64(4.160537712307688e-08)

## the two variables size and day are independent is that right

In [9]:
size_average = df['size'].mean()
size_average

np.float64(2.569672131147541)

In [10]:
chi2_contingency = chi2_contingency(pd.crosstab(df['day'], df['size']))
alpha = 0.05
chi2_contingency

Chi2ContingencyResult(statistic=np.float64(29.632849936919712), pvalue=np.float64(0.013316478351860587), dof=15, expected_freq=array([[ 1.01639344, 39.63934426,  9.6557377 ,  9.40163934,  1.2704918 ,
         1.01639344],
       [ 0.31147541, 12.14754098,  2.95901639,  2.88114754,  0.38934426,
         0.31147541],
       [ 1.42622951, 55.62295082, 13.54918033, 13.19262295,  1.78278689,
         1.42622951],
       [ 1.24590164, 48.59016393, 11.83606557, 11.52459016,  1.55737705,
         1.24590164]]))

In [11]:
tabel = pd.crosstab(df['day'], df['size'])
print(tabel)

size  1   2   3   4  5  6
day
Thur  1  48   4   5  1  3
Fri   1  16   1   1  0  0
Sat   2  53  18  13  1  0
Sun   0  39  15  18  3  1

In [12]:
diffrence = tabel - tabel.mean()
diffrence

size    1     2    3     4     5    6
day
Thur  0.0   9.0 -5.5 -4.25 -0.25  2.0
Fri   0.0 -23.0 -8.5 -8.25 -1.25 -1.0
Sat   1.0  14.0  8.5  3.75 -0.25 -1.0
Sun  -1.0   0.0  5.5  8.75  1.75  0.0

In [13]:
df=sns.load_dataset('healthexp')
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

## (Bonus) : Test d’hypothèse sur la durée de vie aux États-Unis
## Un politicien américain affirme que depuis 1970, la durée de vie aux États-Unis augmente en moyenne de 0,3 an par an.

In [17]:
p = chi2_contingency(pd.crosstab(df['Life_Expectancy'], df['Spending_USD'])).pvalue
alpha = 0.3

TypeError: 'Chi2ContingencyResult' object is not callable